//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOOKSHOPEntities : DbContext
    {
        public BOOKSHOPEntities()
            : base("name=BOOKSHOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<order_num> order_num { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
